--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-11-21 16:56:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'Standard public schema';


--
-- TOC entry 894 (class 1247 OID 41764)
-- Name: gender; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.gender AS ENUM (
    'MALE',
    'FEMALE',
    'OTHER',
    'PREFER_NOT_TO_SAY'
);


--
-- TOC entry 891 (class 1247 OID 41748)
-- Name: staff_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.staff_role AS ENUM (
    'BRAND_ADMIN',
    'MANAGER',
    'STAFF'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 262 (class 1259 OID 50374)
-- Name: brand_point_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.brand_point_configs (
    brand_id bigint NOT NULL,
    earn_rate numeric(5,2) DEFAULT 1.00 NOT NULL,
    redeem_rate numeric(5,2) DEFAULT 0.10 NOT NULL,
    expiry_days integer,
    updated_at timestamp without time zone
);


--
-- TOC entry 221 (class 1259 OID 41796)
-- Name: brands; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.brands (
    brand_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    contact_person character varying(100),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active boolean NOT NULL
);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE brands; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.brands IS '品牌 (租戶) 主資料表';


--
-- TOC entry 220 (class 1259 OID 41795)
-- Name: brands_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.brands ALTER COLUMN brand_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brands_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 41870)
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    category_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    sort_order integer DEFAULT 0
);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 229
-- Name: TABLE categories; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.categories IS '商品分類';


--
-- TOC entry 228 (class 1259 OID 41869)
-- Name: categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 42150)
-- Name: daily_summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_summaries (
    summary_id bigint NOT NULL,
    store_id bigint NOT NULL,
    staff_user_id bigint NOT NULL,
    summary_date date NOT NULL,
    total_revenue numeric(10,2) NOT NULL,
    cash_shortage_or_overage numeric(10,2) NOT NULL,
    notes text
);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 256
-- Name: TABLE daily_summaries; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.daily_summaries IS '每日關帳紀錄';


--
-- TOC entry 255 (class 1259 OID 42149)
-- Name: daily_summaries_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_summaries ALTER COLUMN summary_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_summaries_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 42132)
-- Name: inventory_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_batches (
    batch_id bigint NOT NULL,
    shipment_id bigint NOT NULL,
    inventory_item_id bigint NOT NULL,
    quantity_received numeric(10,2) NOT NULL,
    current_quantity numeric(10,2) NOT NULL,
    production_date date,
    expiry_date date NOT NULL,
    CONSTRAINT chk_ib_quantities CHECK (((quantity_received > (0)::numeric) AND (current_quantity >= (0)::numeric)))
);


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 254
-- Name: TABLE inventory_batches; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.inventory_batches IS '庫存批次管理，用於先進先出/效期管理';


--
-- TOC entry 253 (class 1259 OID 42131)
-- Name: inventory_batches_batch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_batches ALTER COLUMN batch_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_batches_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 42100)
-- Name: inventory_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_items (
    inventory_item_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    unit character varying(20) NOT NULL
);


--
-- TOC entry 5099 (class 0 OID 0)
-- Dependencies: 250
-- Name: TABLE inventory_items; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.inventory_items IS '總部定義的原物料主資料';


--
-- TOC entry 249 (class 1259 OID 42099)
-- Name: inventory_items_inventory_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_items ALTER COLUMN inventory_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_items_inventory_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 42031)
-- Name: invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoices (
    invoice_id bigint NOT NULL,
    order_id bigint NOT NULL,
    invoice_number character varying(10) NOT NULL,
    issue_date timestamp with time zone NOT NULL,
    total_amount numeric(10,2) NOT NULL
);


--
-- TOC entry 242 (class 1259 OID 42030)
-- Name: invoices_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoices ALTER COLUMN invoice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 42081)
-- Name: member_points_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_points_log (
    log_id bigint NOT NULL,
    member_user_id bigint NOT NULL,
    order_id bigint,
    points_change bigint NOT NULL,
    balance_after bigint NOT NULL,
    reason character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_mpl_points_change CHECK ((points_change <> 0))
);


--
-- TOC entry 247 (class 1259 OID 42080)
-- Name: member_points_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_points_log ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_points_log_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 41853)
-- Name: member_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_profiles (
    user_id bigint NOT NULL,
    full_name character varying(100),
    email character varying(100),
    birth_date date,
    gender public.gender,
    total_points bigint DEFAULT 0 NOT NULL,
    notes text,
    is_deleted boolean DEFAULT false NOT NULL,
    version integer DEFAULT 0 NOT NULL
);


--
-- TOC entry 5100 (class 0 OID 0)
-- Dependencies: 227
-- Name: TABLE member_profiles; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.member_profiles IS '會員角色資料，關聯至 users 表';


--
-- TOC entry 234 (class 1259 OID 41922)
-- Name: option_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.option_groups (
    group_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    selection_type character varying(20) DEFAULT 'SINGLE'::character varying NOT NULL,
    sort_order integer,
    CONSTRAINT chk_option_groups_selection_type CHECK (((selection_type)::text = ANY ((ARRAY['SINGLE'::character varying, 'MULTIPLE'::character varying])::text[])))
);


--
-- TOC entry 5101 (class 0 OID 0)
-- Dependencies: 234
-- Name: TABLE option_groups; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.option_groups IS '客製化選項群組 (如: 甜度, 冰量)';


--
-- TOC entry 233 (class 1259 OID 41921)
-- Name: option_groups_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.option_groups ALTER COLUMN group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.option_groups_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 42015)
-- Name: order_item_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item_options (
    order_item_id bigint NOT NULL,
    option_id bigint NOT NULL
);


--
-- TOC entry 5102 (class 0 OID 0)
-- Dependencies: 241
-- Name: TABLE order_item_options; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.order_item_options IS '訂單品項的客製化選項';


--
-- TOC entry 240 (class 1259 OID 41995)
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    order_item_id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    notes text,
    CONSTRAINT chk_order_items_prices CHECK ((unit_price >= (0)::numeric)),
    CONSTRAINT chk_order_items_quantity CHECK ((quantity > 0))
);


--
-- TOC entry 239 (class 1259 OID 41994)
-- Name: order_items_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_items ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 41773)
-- Name: order_status_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_status_codes (
    status_code character varying(50) NOT NULL,
    description text,
    is_terminal_state boolean DEFAULT false NOT NULL,
    sort_order integer
);


--
-- TOC entry 5103 (class 0 OID 0)
-- Dependencies: 217
-- Name: TABLE order_status_codes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.order_status_codes IS '訂單狀態查找表，取代 ENUM 以增加靈活性';


--
-- TOC entry 238 (class 1259 OID 41951)
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    order_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    store_id bigint NOT NULL,
    member_user_id bigint,
    staff_user_id bigint,
    order_number character varying(30) NOT NULL,
    status_code character varying(50) DEFAULT 'PENDING'::character varying NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    discount_amount numeric(10,2) DEFAULT 0.00 NOT NULL,
    final_amount numeric(10,2) NOT NULL,
    points_used bigint DEFAULT 0 NOT NULL,
    points_earned bigint DEFAULT 0 NOT NULL,
    customer_note text,
    order_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_time timestamp with time zone,
    payment_method_id integer,
    CONSTRAINT chk_orders_amounts CHECK (((total_amount >= (0)::numeric) AND (discount_amount >= (0)::numeric)))
);


--
-- TOC entry 5104 (class 0 OID 0)
-- Dependencies: 238
-- Name: TABLE orders; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.orders IS '訂單主表，欄位已細化';


--
-- TOC entry 237 (class 1259 OID 41950)
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 42473)
-- Name: payment_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_methods (
    payment_method_id integer NOT NULL,
    code character varying(20) NOT NULL,
    name character varying(50) NOT NULL
);


--
-- TOC entry 258 (class 1259 OID 42472)
-- Name: payment_methods_payment_method_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.payment_methods_payment_method_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5105 (class 0 OID 0)
-- Dependencies: 258
-- Name: payment_methods_payment_method_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.payment_methods_payment_method_id_seq OWNED BY public.payment_methods.payment_method_id;


--
-- TOC entry 261 (class 1259 OID 50363)
-- Name: platform_admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.platform_admins (
    admin_id bigint NOT NULL,
    username character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(50) DEFAULT 'ROLE_PLATFORM_ADMIN'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 5106 (class 0 OID 0)
-- Dependencies: 261
-- Name: TABLE platform_admins; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.platform_admins IS 'SaaS 平台方超級管理員帳號';


--
-- TOC entry 260 (class 1259 OID 50362)
-- Name: platform_admins_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.platform_admins_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 5107 (class 0 OID 0)
-- Dependencies: 260
-- Name: platform_admins_admin_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.platform_admins_admin_id_seq OWNED BY public.platform_admins.admin_id;


--
-- TOC entry 232 (class 1259 OID 41906)
-- Name: product_category_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_category_mappings (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- TOC entry 5108 (class 0 OID 0)
-- Dependencies: 232
-- Name: TABLE product_category_mappings; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.product_category_mappings IS '商品與分類多對多關聯';


--
-- TOC entry 257 (class 1259 OID 42446)
-- Name: product_option_group_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_option_group_mappings (
    product_id bigint NOT NULL,
    group_id bigint NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 41937)
-- Name: product_options; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_options (
    option_id bigint NOT NULL,
    group_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    price_adjustment numeric(10,2) DEFAULT 0.00 NOT NULL,
    is_default boolean DEFAULT false NOT NULL
);


--
-- TOC entry 5109 (class 0 OID 0)
-- Dependencies: 236
-- Name: TABLE product_options; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.product_options IS '具體客製化選項 (如: 全糖, 去冰)';


--
-- TOC entry 235 (class 1259 OID 41936)
-- Name: product_options_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_options ALTER COLUMN option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_options_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 41781)
-- Name: product_status_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_status_codes (
    status_code character varying(50) NOT NULL,
    description text
);


--
-- TOC entry 5110 (class 0 OID 0)
-- Dependencies: 218
-- Name: TABLE product_status_codes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.product_status_codes IS '商品狀態查找表';


--
-- TOC entry 231 (class 1259 OID 41884)
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    product_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    base_price numeric(10,2) NOT NULL,
    image_url character varying(255),
    status_code character varying(50) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_products_base_price CHECK ((base_price >= (0)::numeric))
);


--
-- TOC entry 5111 (class 0 OID 0)
-- Dependencies: 231
-- Name: TABLE products; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.products IS '商品主資料';


--
-- TOC entry 230 (class 1259 OID 41883)
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 42065)
-- Name: promotion_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promotion_products (
    promotion_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 41788)
-- Name: promotion_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promotion_types (
    type_code character varying(50) NOT NULL,
    description text
);


--
-- TOC entry 5112 (class 0 OID 0)
-- Dependencies: 219
-- Name: TABLE promotion_types; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.promotion_types IS '促銷活動類型查找表';


--
-- TOC entry 245 (class 1259 OID 42046)
-- Name: promotions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promotions (
    promotion_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    type_code character varying(50) NOT NULL,
    value numeric(10,2) NOT NULL,
    min_spend numeric(10,2),
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_promotions_dates CHECK ((end_date > start_date))
);


--
-- TOC entry 244 (class 1259 OID 42045)
-- Name: promotions_promotion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.promotions ALTER COLUMN promotion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_promotion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 42113)
-- Name: purchase_shipments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_shipments (
    shipment_id bigint NOT NULL,
    store_id bigint NOT NULL,
    staff_user_id bigint,
    shipment_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    supplier character varying(255),
    notes text
);


--
-- TOC entry 5113 (class 0 OID 0)
-- Dependencies: 252
-- Name: TABLE purchase_shipments; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.purchase_shipments IS '店家進貨單';


--
-- TOC entry 251 (class 1259 OID 42112)
-- Name: purchase_shipments_shipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purchase_shipments ALTER COLUMN shipment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_shipments_shipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 41836)
-- Name: staff_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staff_profiles (
    user_id bigint NOT NULL,
    store_id bigint,
    employee_number character varying(50),
    full_name character varying(100) NOT NULL,
    role public.staff_role NOT NULL,
    hire_date date
);


--
-- TOC entry 5114 (class 0 OID 0)
-- Dependencies: 226
-- Name: TABLE staff_profiles; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.staff_profiles IS '員工角色資料，關聯至 users 表';


--
-- TOC entry 223 (class 1259 OID 41806)
-- Name: stores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stores (
    store_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    address character varying(255),
    phone character varying(20),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 5115 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE stores; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.stores IS '分店資料表，已移除密碼欄位';


--
-- TOC entry 222 (class 1259 OID 41805)
-- Name: stores_store_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stores ALTER COLUMN store_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 41821)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    primary_phone character varying(20),
    password_hash character varying(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 5116 (class 0 OID 0)
-- Dependencies: 225
-- Name: TABLE users; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.users IS '統一使用者核心表，整合員工與會員';


--
-- TOC entry 224 (class 1259 OID 41820)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4799 (class 2604 OID 42476)
-- Name: payment_methods payment_method_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_methods ALTER COLUMN payment_method_id SET DEFAULT nextval('public.payment_methods_payment_method_id_seq'::regclass);


--
-- TOC entry 4800 (class 2604 OID 50366)
-- Name: platform_admins admin_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_admins ALTER COLUMN admin_id SET DEFAULT nextval('public.platform_admins_admin_id_seq'::regclass);


--
-- TOC entry 4904 (class 2606 OID 50380)
-- Name: brand_point_configs brand_point_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brand_point_configs
    ADD CONSTRAINT brand_point_configs_pkey PRIMARY KEY (brand_id);


--
-- TOC entry 4896 (class 2606 OID 42480)
-- Name: payment_methods payment_methods_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT payment_methods_code_key UNIQUE (code);


--
-- TOC entry 4898 (class 2606 OID 42478)
-- Name: payment_methods payment_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT payment_methods_pkey PRIMARY KEY (payment_method_id);


--
-- TOC entry 4820 (class 2606 OID 41802)
-- Name: brands pk_brands; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT pk_brands PRIMARY KEY (brand_id);


--
-- TOC entry 4839 (class 2606 OID 41875)
-- Name: categories pk_categories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT pk_categories PRIMARY KEY (category_id);


--
-- TOC entry 4889 (class 2606 OID 42156)
-- Name: daily_summaries pk_daily_summaries; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_summaries
    ADD CONSTRAINT pk_daily_summaries PRIMARY KEY (summary_id);


--
-- TOC entry 4887 (class 2606 OID 42137)
-- Name: inventory_batches pk_inventory_batches; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_batches
    ADD CONSTRAINT pk_inventory_batches PRIMARY KEY (batch_id);


--
-- TOC entry 4880 (class 2606 OID 42104)
-- Name: inventory_items pk_inventory_items; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT pk_inventory_items PRIMARY KEY (inventory_item_id);


--
-- TOC entry 4867 (class 2606 OID 42035)
-- Name: invoices pk_invoices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT pk_invoices PRIMARY KEY (invoice_id);


--
-- TOC entry 4878 (class 2606 OID 42087)
-- Name: member_points_log pk_member_points_log; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_points_log
    ADD CONSTRAINT pk_member_points_log PRIMARY KEY (log_id);


--
-- TOC entry 4835 (class 2606 OID 41861)
-- Name: member_profiles pk_member_profiles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_profiles
    ADD CONSTRAINT pk_member_profiles PRIMARY KEY (user_id);


--
-- TOC entry 4848 (class 2606 OID 41928)
-- Name: option_groups pk_option_groups; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.option_groups
    ADD CONSTRAINT pk_option_groups PRIMARY KEY (group_id);


--
-- TOC entry 4865 (class 2606 OID 42019)
-- Name: order_item_options pk_order_item_options; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_options
    ADD CONSTRAINT pk_order_item_options PRIMARY KEY (order_item_id, option_id);


--
-- TOC entry 4863 (class 2606 OID 42003)
-- Name: order_items pk_order_items; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT pk_order_items PRIMARY KEY (order_item_id);


--
-- TOC entry 4814 (class 2606 OID 41780)
-- Name: order_status_codes pk_order_status_codes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_status_codes
    ADD CONSTRAINT pk_order_status_codes PRIMARY KEY (status_code);


--
-- TOC entry 4858 (class 2606 OID 41963)
-- Name: orders pk_orders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT pk_orders PRIMARY KEY (order_id);


--
-- TOC entry 4846 (class 2606 OID 41910)
-- Name: product_category_mappings pk_product_category_mappings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_category_mappings
    ADD CONSTRAINT pk_product_category_mappings PRIMARY KEY (product_id, category_id);


--
-- TOC entry 4853 (class 2606 OID 41943)
-- Name: product_options pk_product_options; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_options
    ADD CONSTRAINT pk_product_options PRIMARY KEY (option_id);


--
-- TOC entry 4816 (class 2606 OID 41787)
-- Name: product_status_codes pk_product_status_codes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_status_codes
    ADD CONSTRAINT pk_product_status_codes PRIMARY KEY (status_code);


--
-- TOC entry 4844 (class 2606 OID 41894)
-- Name: products pk_products; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT pk_products PRIMARY KEY (product_id);


--
-- TOC entry 4875 (class 2606 OID 42069)
-- Name: promotion_products pk_promotion_products; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotion_products
    ADD CONSTRAINT pk_promotion_products PRIMARY KEY (promotion_id, product_id);


--
-- TOC entry 4818 (class 2606 OID 41794)
-- Name: promotion_types pk_promotion_types; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotion_types
    ADD CONSTRAINT pk_promotion_types PRIMARY KEY (type_code);


--
-- TOC entry 4873 (class 2606 OID 42054)
-- Name: promotions pk_promotions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT pk_promotions PRIMARY KEY (promotion_id);


--
-- TOC entry 4884 (class 2606 OID 42120)
-- Name: purchase_shipments pk_purchase_shipments; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_shipments
    ADD CONSTRAINT pk_purchase_shipments PRIMARY KEY (shipment_id);


--
-- TOC entry 4831 (class 2606 OID 41840)
-- Name: staff_profiles pk_staff_profiles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_profiles
    ADD CONSTRAINT pk_staff_profiles PRIMARY KEY (user_id);


--
-- TOC entry 4825 (class 2606 OID 41813)
-- Name: stores pk_stores; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT pk_stores PRIMARY KEY (store_id);


--
-- TOC entry 4827 (class 2606 OID 41828)
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (user_id);


--
-- TOC entry 4900 (class 2606 OID 50370)
-- Name: platform_admins platform_admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_admins
    ADD CONSTRAINT platform_admins_pkey PRIMARY KEY (admin_id);


--
-- TOC entry 4902 (class 2606 OID 50372)
-- Name: platform_admins platform_admins_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.platform_admins
    ADD CONSTRAINT platform_admins_username_key UNIQUE (username);


--
-- TOC entry 4893 (class 2606 OID 42450)
-- Name: product_option_group_mappings product_option_group_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_option_group_mappings
    ADD CONSTRAINT product_option_group_mappings_pkey PRIMARY KEY (product_id, group_id);


--
-- TOC entry 4822 (class 2606 OID 41804)
-- Name: brands uk_brands_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brands
    ADD CONSTRAINT uk_brands_name UNIQUE (name);


--
-- TOC entry 4841 (class 2606 OID 41877)
-- Name: categories uk_categories_brand_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT uk_categories_brand_name UNIQUE (brand_id, name);


--
-- TOC entry 4891 (class 2606 OID 42158)
-- Name: daily_summaries uk_daily_summaries_store_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_summaries
    ADD CONSTRAINT uk_daily_summaries_store_date UNIQUE (store_id, summary_date);


--
-- TOC entry 4882 (class 2606 OID 42106)
-- Name: inventory_items uk_inventory_items_brand_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT uk_inventory_items_brand_name UNIQUE (brand_id, name);


--
-- TOC entry 4869 (class 2606 OID 42039)
-- Name: invoices uk_invoices_invoice_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT uk_invoices_invoice_number UNIQUE (invoice_number);


--
-- TOC entry 4871 (class 2606 OID 42037)
-- Name: invoices uk_invoices_order_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT uk_invoices_order_id UNIQUE (order_id);


--
-- TOC entry 4837 (class 2606 OID 41863)
-- Name: member_profiles uk_member_profiles_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_profiles
    ADD CONSTRAINT uk_member_profiles_email UNIQUE (email);


--
-- TOC entry 4850 (class 2606 OID 41930)
-- Name: option_groups uk_option_groups_brand_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.option_groups
    ADD CONSTRAINT uk_option_groups_brand_name UNIQUE (brand_id, name);


--
-- TOC entry 4860 (class 2606 OID 41965)
-- Name: orders uk_orders_brand_order_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_orders_brand_order_number UNIQUE (brand_id, order_number);


--
-- TOC entry 4833 (class 2606 OID 41842)
-- Name: staff_profiles uk_staff_profiles_store_employee_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_profiles
    ADD CONSTRAINT uk_staff_profiles_store_employee_number UNIQUE (store_id, employee_number);


--
-- TOC entry 4829 (class 2606 OID 41830)
-- Name: users uk_users_brand_phone; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_brand_phone UNIQUE (brand_id, primary_phone);


--
-- TOC entry 4885 (class 1259 OID 42148)
-- Name: idx_inventory_batches_expiry_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_batches_expiry_date ON public.inventory_batches USING btree (expiry_date);


--
-- TOC entry 4876 (class 1259 OID 42098)
-- Name: idx_member_points_log_member_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_member_points_log_member_user_id ON public.member_points_log USING btree (member_user_id);


--
-- TOC entry 4861 (class 1259 OID 42014)
-- Name: idx_order_items_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);


--
-- TOC entry 4854 (class 1259 OID 41992)
-- Name: idx_orders_member_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_member_user_id ON public.orders USING btree (member_user_id);


--
-- TOC entry 4855 (class 1259 OID 41993)
-- Name: idx_orders_order_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_order_time ON public.orders USING btree (order_time);


--
-- TOC entry 4856 (class 1259 OID 41991)
-- Name: idx_orders_store_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_store_id ON public.orders USING btree (store_id);


--
-- TOC entry 4894 (class 1259 OID 42481)
-- Name: idx_payment_methods_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_methods_code ON public.payment_methods USING btree (code);


--
-- TOC entry 4851 (class 1259 OID 41949)
-- Name: idx_product_options_group_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_options_group_id ON public.product_options USING btree (group_id);


--
-- TOC entry 4842 (class 1259 OID 41905)
-- Name: idx_products_brand_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_brand_id ON public.products USING btree (brand_id);


--
-- TOC entry 4823 (class 1259 OID 41819)
-- Name: idx_stores_brand_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stores_brand_id ON public.stores USING btree (brand_id);


--
-- TOC entry 4943 (class 2606 OID 50381)
-- Name: brand_point_configs fk_brand_point_configs_brands; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.brand_point_configs
    ADD CONSTRAINT fk_brand_point_configs_brands FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4910 (class 2606 OID 41878)
-- Name: categories fk_categories_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fk_categories_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4939 (class 2606 OID 42164)
-- Name: daily_summaries fk_ds_staff; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_summaries
    ADD CONSTRAINT fk_ds_staff FOREIGN KEY (staff_user_id) REFERENCES public.users(user_id) ON DELETE RESTRICT;


--
-- TOC entry 4940 (class 2606 OID 42159)
-- Name: daily_summaries fk_ds_store; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_summaries
    ADD CONSTRAINT fk_ds_store FOREIGN KEY (store_id) REFERENCES public.stores(store_id) ON DELETE CASCADE;


--
-- TOC entry 4937 (class 2606 OID 42143)
-- Name: inventory_batches fk_ib_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_batches
    ADD CONSTRAINT fk_ib_item FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(inventory_item_id) ON DELETE CASCADE;


--
-- TOC entry 4938 (class 2606 OID 42138)
-- Name: inventory_batches fk_ib_shipment; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_batches
    ADD CONSTRAINT fk_ib_shipment FOREIGN KEY (shipment_id) REFERENCES public.purchase_shipments(shipment_id) ON DELETE CASCADE;


--
-- TOC entry 4934 (class 2606 OID 42107)
-- Name: inventory_items fk_inventory_items_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT fk_inventory_items_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4927 (class 2606 OID 42040)
-- Name: invoices fk_invoices_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fk_invoices_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE CASCADE;


--
-- TOC entry 4909 (class 2606 OID 41864)
-- Name: member_profiles fk_member_profiles_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_profiles
    ADD CONSTRAINT fk_member_profiles_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- TOC entry 4932 (class 2606 OID 42088)
-- Name: member_points_log fk_mpl_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_points_log
    ADD CONSTRAINT fk_mpl_member FOREIGN KEY (member_user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- TOC entry 4933 (class 2606 OID 42093)
-- Name: member_points_log fk_mpl_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_points_log
    ADD CONSTRAINT fk_mpl_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE SET NULL;


--
-- TOC entry 4925 (class 2606 OID 42025)
-- Name: order_item_options fk_oio_option; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_options
    ADD CONSTRAINT fk_oio_option FOREIGN KEY (option_id) REFERENCES public.product_options(option_id) ON DELETE RESTRICT;


--
-- TOC entry 4926 (class 2606 OID 42020)
-- Name: order_item_options fk_oio_order_item; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_options
    ADD CONSTRAINT fk_oio_order_item FOREIGN KEY (order_item_id) REFERENCES public.order_items(order_item_id) ON DELETE CASCADE;


--
-- TOC entry 4915 (class 2606 OID 41931)
-- Name: option_groups fk_option_groups_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.option_groups
    ADD CONSTRAINT fk_option_groups_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4923 (class 2606 OID 42004)
-- Name: order_items fk_order_items_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE CASCADE;


--
-- TOC entry 4924 (class 2606 OID 42009)
-- Name: order_items fk_order_items_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE RESTRICT;


--
-- TOC entry 4917 (class 2606 OID 41966)
-- Name: orders fk_orders_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4918 (class 2606 OID 41976)
-- Name: orders fk_orders_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_member FOREIGN KEY (member_user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- TOC entry 4919 (class 2606 OID 42482)
-- Name: orders fk_orders_payment_method; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_payment_method FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(payment_method_id) ON DELETE SET NULL;


--
-- TOC entry 4920 (class 2606 OID 41981)
-- Name: orders fk_orders_staff; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_staff FOREIGN KEY (staff_user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- TOC entry 4921 (class 2606 OID 41986)
-- Name: orders fk_orders_status; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_status FOREIGN KEY (status_code) REFERENCES public.order_status_codes(status_code);


--
-- TOC entry 4922 (class 2606 OID 41971)
-- Name: orders fk_orders_store; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES public.stores(store_id) ON DELETE RESTRICT;


--
-- TOC entry 4913 (class 2606 OID 41916)
-- Name: product_category_mappings fk_pcm_category; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_category_mappings
    ADD CONSTRAINT fk_pcm_category FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON DELETE CASCADE;


--
-- TOC entry 4914 (class 2606 OID 41911)
-- Name: product_category_mappings fk_pcm_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_category_mappings
    ADD CONSTRAINT fk_pcm_product FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE;


--
-- TOC entry 4930 (class 2606 OID 42075)
-- Name: promotion_products fk_pp_product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotion_products
    ADD CONSTRAINT fk_pp_product FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE;


--
-- TOC entry 4931 (class 2606 OID 42070)
-- Name: promotion_products fk_pp_promotion; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotion_products
    ADD CONSTRAINT fk_pp_promotion FOREIGN KEY (promotion_id) REFERENCES public.promotions(promotion_id) ON DELETE CASCADE;


--
-- TOC entry 4916 (class 2606 OID 41944)
-- Name: product_options fk_product_options_group; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_options
    ADD CONSTRAINT fk_product_options_group FOREIGN KEY (group_id) REFERENCES public.option_groups(group_id) ON DELETE CASCADE;


--
-- TOC entry 4911 (class 2606 OID 41895)
-- Name: products fk_products_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4912 (class 2606 OID 41900)
-- Name: products fk_products_status; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_status FOREIGN KEY (status_code) REFERENCES public.product_status_codes(status_code);


--
-- TOC entry 4928 (class 2606 OID 42055)
-- Name: promotions fk_promotions_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT fk_promotions_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4929 (class 2606 OID 42060)
-- Name: promotions fk_promotions_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT fk_promotions_type FOREIGN KEY (type_code) REFERENCES public.promotion_types(type_code);


--
-- TOC entry 4935 (class 2606 OID 42126)
-- Name: purchase_shipments fk_ps_staff; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_shipments
    ADD CONSTRAINT fk_ps_staff FOREIGN KEY (staff_user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- TOC entry 4936 (class 2606 OID 42121)
-- Name: purchase_shipments fk_ps_store; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_shipments
    ADD CONSTRAINT fk_ps_store FOREIGN KEY (store_id) REFERENCES public.stores(store_id) ON DELETE CASCADE;


--
-- TOC entry 4907 (class 2606 OID 41848)
-- Name: staff_profiles fk_staff_profiles_store; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_profiles
    ADD CONSTRAINT fk_staff_profiles_store FOREIGN KEY (store_id) REFERENCES public.stores(store_id) ON DELETE CASCADE;


--
-- TOC entry 4908 (class 2606 OID 41843)
-- Name: staff_profiles fk_staff_profiles_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_profiles
    ADD CONSTRAINT fk_staff_profiles_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- TOC entry 4905 (class 2606 OID 41814)
-- Name: stores fk_stores_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT fk_stores_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4906 (class 2606 OID 41831)
-- Name: users fk_users_brand; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE;


--
-- TOC entry 4941 (class 2606 OID 42456)
-- Name: product_option_group_mappings product_option_group_mappings_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_option_group_mappings
    ADD CONSTRAINT product_option_group_mappings_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.option_groups(group_id);


--
-- TOC entry 4942 (class 2606 OID 42451)
-- Name: product_option_group_mappings product_option_group_mappings_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_option_group_mappings
    ADD CONSTRAINT product_option_group_mappings_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(product_id);


-- Completed on 2025-11-21 16:56:57

--
-- PostgreSQL database dump complete
--

