-- V2__add_report_tables.sql
-- 新增報表系統所需的統計表

-- 1. 建立分店日結統計表 (Daily Store Stats)
CREATE TABLE public.daily_store_stats (
                                          id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          store_id bigint NOT NULL,
                                          brand_id bigint NOT NULL,
                                          date date NOT NULL,

    -- 核心指標
                                          total_orders integer DEFAULT 0 NOT NULL,
                                          total_revenue numeric(12,2) DEFAULT 0.00 NOT NULL,   -- 原始總額
                                          total_discount numeric(12,2) DEFAULT 0.00 NOT NULL,  -- 折扣總額
                                          final_revenue numeric(12,2) DEFAULT 0.00 NOT NULL,   -- 實收金額 (Net Sales)
                                          cancelled_orders integer DEFAULT 0 NOT NULL,

    -- 支付方式細分 (預留欄位)
                                          cash_total numeric(12,2) DEFAULT 0.00,
                                          line_pay_total numeric(12,2) DEFAULT 0.00,

                                          created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,

    -- 設定主鍵
                                          CONSTRAINT pk_daily_store_stats PRIMARY KEY (id),

    -- 設定外鍵關聯 (確保資料完整性，當分店或品牌被刪除時，統計資料一併移除)
                                          CONSTRAINT fk_dss_store FOREIGN KEY (store_id) REFERENCES public.stores(store_id) ON DELETE CASCADE,
                                          CONSTRAINT fk_dss_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE,

    -- 確保同一間店同一天只有一筆紀錄
                                          CONSTRAINT uk_daily_store_stats_store_date UNIQUE (store_id, date)
);

-- 建立索引以加速報表查詢
CREATE INDEX idx_daily_store_date ON public.daily_store_stats (store_id, date);
CREATE INDEX idx_daily_brand_date ON public.daily_store_stats (brand_id, date);


-- 2. 建立商品銷售統計表 (Daily Product Stats)
CREATE TABLE public.daily_product_stats (
                                            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                            store_id bigint NOT NULL,
                                            brand_id bigint NOT NULL,
                                            product_id bigint NOT NULL,

    -- 快照欄位 (Snapshot): 記錄當下的名稱，避免商品改名後歷史報表錯亂
                                            product_name character varying(100) NOT NULL,
                                            category_name character varying(100),

                                            date date NOT NULL,

    -- 銷售數據
                                            quantity_sold integer DEFAULT 0 NOT NULL,
                                            total_sales_amount numeric(12,2) DEFAULT 0.00 NOT NULL,

                                            created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,

                                            CONSTRAINT pk_daily_product_stats PRIMARY KEY (id),

    -- 外鍵關聯
                                            CONSTRAINT fk_dps_store FOREIGN KEY (store_id) REFERENCES public.stores(store_id) ON DELETE CASCADE,
                                            CONSTRAINT fk_dps_brand FOREIGN KEY (brand_id) REFERENCES public.brands(brand_id) ON DELETE CASCADE,
                                            CONSTRAINT fk_dps_product FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON DELETE CASCADE
);

-- 建立索引
CREATE INDEX idx_prod_store_date ON public.daily_product_stats (store_id, date);
CREATE INDEX idx_prod_brand_date ON public.daily_product_stats (brand_id, date);